config/routes.rb
Rails.application.routes.draw do
  
  
  resources :topics do
      resources :posts, except: [:index]
      resources :sponsored_posts, except: [:index] 
      
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  post 'users/confirm' => 'users#confirm'
  


  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :sponsored_posts
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 5 }, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    
    before_action :require_sign_in, except: [:index, :show]
    before_action :authorize_user, except: [:index, :show]
    
    def index
     @topics = Topic.all
    end
    
    def show
     @topic = Topic.find(params[:id])
    end
    
    def new
     @topic = Topic.new
    end
    
    def create
     @topic = Topic.new(topic_params)
 
     if @topic.save
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash.now[:alert] = "Error creating topic. Please try again."
       render :new
     end
    end
    
    def edit
     @topic = Topic.find(params[:id])
    end
    
    def update
     @topic = Topic.find(params[:id])
     @topic.assign_attributes(topic_params)
 
     if @topic.save
        flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash.now[:alert] = "Error saving topic. Please try again."
       render :edit
     end
    end
    
    def destroy
     @topic = Topic.find(params[:id])
 
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
    end
    
  private
   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end  
  
  
  def authorize_user
     unless current_user.admin? || current_user.moderator?
       flash[:alert] = "You must be an admin to do that."
       redirect_to topics_path
     end
  end
  
end

app/helpers/topics_helper.rb
module TopicsHelper
    
    def user_is_authorized_for_topics?
        current_user && current_user.admin?
    end
    
end

app/views/topics/_form.html.erb
<%= form_for [topic] do |f| %>
  <% if topic.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(topic.errors.count, "Error") %>.</h4>
      <ul>
        <% topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="circle">
    <div class="circle-form">
      <%= form_group_tag(topic.errors[:name]) do %>
        <h3><%= f.label :name, class: 'rant' %></h3>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter rant name" %>
      <% end %>
        
      <%= form_group_tag(topic.errors[:description]) do %>
        <h3><%= f.label :description, class: 'rant' %></h3>
        <%= f.text_area :description, rows: 1, class: 'form-control', placeholder: "Enter rant description" %>
      <% end %>
       
      <div class="form-group">
        <%= f.label :public, class: 'checkbox' do %>
          <%= f.check_box :public %> Public Rant
        <% end %>
      </div>
      <%= f.submit "Save", class: 'btn btn-danger' %> 
    </div> 
  </div> 
        
<% end %>

app/views/topics/_topic.html.erb
<div class="media">
         <div class="media-body">
           <h4 class="media-heading">
              <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>

app/views/topics/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="circle-sml">
      <div class="circle-form">
        <h3 class="rant">Edit Rant</h3>
        <p>Guidelines for Rants:</p>
        <ol>
          <li>It grinds your gears.</li>
          <li>Never insult cats.</li>
          <li>Smile when you type.</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="row">
  <div class="col-md-12 text-center">
    <div class="circle-sml">
      <div class="circle-txt">
        <h1 class="rant">RANTS</h1>
        <% if user_is_authorized_for_topics? %>
          <%= link_to "New Rant", new_topic_path, class: 'btn btn-danger' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row text-center">
  <% @topics.each do |topic| %>
    <div class="col-md-4">
      <div class="circle-sml">
        <div class="circle-sml-txt">
          <h3 class="rant"><%= link_to topic.name, topic, style: 'text-decoration: none;' %></h3>
          <h5><%= topic.description %></h5>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/topics/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="circle-sml">
      <div class="circle-form">
        <h3 class="rant">New Rant</h3>
        <p>Guidelines for Rants:</p>
        <ol>
          <li>It grinds your gears.</li>
          <li>Never insult cats.</li>
          <li>Smile when you type.</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic } %>
  </div>
</div>
 

app/views/topics/show.html.erb
<div class="row">
  <% if current_user %>
    <%= link_to new_topic_post_path(@topic) do %>
      <div class="col-md-4">
         <div class="circle-xsml-btn">
           <div class="circle-xsml-btn-txt">
             <h3>Add a</h3>
             <h3>Thought</h3>
           </div> 
         </div> 
      </div>
    <% end %>
  <% else %>
    <div class="col-md-4">
      <div class="circle-sml">
         <div class="circle-txt">
           <h3 class="rant">Sign up to add Thoughts</h3>
           <%= link_to "Sign Up", new_user_path, class: 'btn btn-danger' %>
         </div>
      </div>
    </div>
  <% end %>
  <div class="col-md-8">
    <div class="circle">
      <div class="circle-txt">
        <h1 class="rant"><%= @topic.name %></h1>
        <p><%= @topic.description %></p>
        <% if user_is_authorized_for_topics? %>
          <%= link_to "Edit Rant", edit_topic_path, class: 'btn btn-default' %>
          <%= link_to "Delete Rant", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
        <% end %> 
      </div>
    </div>
  </div> 
</div>
<div class="row">
  <% @topic.posts.each do |post| %>
    <div class="col-md-4">
      <div class="circle-sml">
        <div class="circle-form">
          <h3 class="rant"><%= link_to post.title, topic_post_path(@topic, post) %></h3>
          <%= render partial: 'votes/voting', locals: { post: post } %>
          Thought <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
          <%= post.comments.count %> Comments
        </div>
      </div>
    </div>
  <% end %>
</div>