config/routes.rb
Rails.application.routes.draw do
  
  
  resources :topics do
      resources :posts, except: [:index]
      resources :sponsored_posts, except: [:index] 
      
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  post 'users/confirm' => 'users#confirm'
  


  root 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    default_scope { order('rank DESC') }
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
   validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 5 }, presence: true
   validates :topic, presence: true
   validates :user, presence: true
   
   def up_votes
 
     votes.where(value: 1).count
   end
 
   def down_votes
 
     votes.where(value: -1).count
   end
 
   def points

     votes.sum(:value)
   end
   
   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_sign_in, except: :show
  
  before_action :authorize_user, except: [:show, :new, :create]
  
  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])  
    @post = Post.new
  end
  
  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user
    
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:alert] = "There was a error saving the post. Please try again."
      render :new
    end  
  end  

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
   
    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was error saving the post. Please try again."
      render :edit
    end  
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was destroyed successfully"
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was error destroying the post"
      render :show
    end  
  end    
  
  private
   def post_params
     params.require(:post).permit(:title, :body)
   end
  
  def authorize_user
     post = Post.find(params[:id])
     unless current_user == post.user || current_user.admin? || current_user.moderator?
       flash[:alert] = "You must be an admin to do that."
       redirect_to [post.topic, post]
     end
   end 

end #end of ends 

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin?)
    end
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="circle">
    <div class="circle-form">
      <%= form_group_tag(post.errors[:title]) do %>
        <h3 class="rant"><%= f.label :title %></h3>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter thought title" %>
      <% end %>
      <%= form_group_tag(post.errors[:body]) do %>
        <h3 class="rant"><%= f.label 'Thought' %></h4>
        <%= f.text_area :body, rows: 1, class: 'form-control', placeholder: "Enter thought body" %>
      <% end %>
      <%= f.submit "Save", class: 'btn btn-danger' %>
    </div> 
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
   <%= render partial: 'votes/voting', locals: { post: post } %>
   <div class="media-body">
     <h4 class="media-heading">
        <div class="pull-left">
         <%= image_tag post.user.avatar_url(128), class: 'gravatar-thumb' %>
       </div>
        <%= link_to post.title, topic_post_path(post.topic, post) %>
     </h4>
     <small>
       submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
       <%= post.comments.count %> Comments
     </small>
   </div>
 </div>

app/views/posts/edit.html.erb
<div class="container">

<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
   </div>
 </div>
</div>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="circle-sml">
      <div class="circle-form">
        <h3 class="rant">New Thought</h3>
        <p>Guidelines for thoughts</p>
        <ol>
          <li>Please no cats.</li>
          <li>No grinding teeth.</li>
          <li>No GIFs.</li>
        </ol>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %> 
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
    <div class="col-md-8">
        <div class="circle">
            <div class="circle-form">
              <h1 class="rant"><%= @post.title %></h1>
              <%= render partial: 'votes/voting', locals: { post: @post } %>
              <h4><%= @post.body %></h4>
              <p>submitted <%= time_ago_in_words(@post.created_at) %> ago by</p>
              <h4 class="rant"><%= @post.user.name %></h4>
              <% if user_is_authorized_for_post?(@post) %>
                <%= link_to "Edit Post", edit_topic_post_path(@post.topic, @post), class: 'btn btn-default' %>
                <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
              <% end %>
            </div>
        </div>
    </div>
    <div class="col-md-4">
      <div class="circle-sml">
        <div class="circle-form">
           <h1 class="rant"><%= pluralize(@post.points, 'POINT') %></h1>
           <h3><%= pluralize(@post.up_votes, 'Up vote') %></h3>
           <h4><%= pluralize(@post.down_votes, 'Down vote') %></h4>     
           <% if current_user %>
             <%= render partial: 'favorites/favorite', locals: { post: @post } %>
           <% end %>
        </div>      
      </div>    
    </div>
</div>
<div class="row">
 <%= render @post.comments %> 
 <div class="col-md-4">
   <% if current_user %>
     <%= render 'comments/form', comment: Comment.new, post: @post %>     
   <% else %>
     <div class="circle-sml">
       <div class="circle-txt">
         <h3 class="rant">Sign up to add Comments</h3>
         <%= link_to "Sign Up", new_user_path, class: 'btn btn-danger' %>
       </div>      
     </div>
   <% end %>
  </div>
</div>

 
     
    
      
      
     
   
   
   
      
 