config/routes.rb
Rails.application.routes.draw do
  
  
  resources :topics do
      resources :posts, except: [:index]
      resources :sponsored_posts, except: [:index] 
      
  end
  
  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end
  
  resources :users, only: [:new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :questions

  resources :advertisements

  post 'users/confirm' => 'users#confirm'
  


  root 'welcome#index'
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
 
  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
  
  after_create :send_favorite_emails
 
   private
 
   def send_favorite_emails
     post.favorites.each do |favorite|
       FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
     end
   end

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    
    default_scope { order('rank DESC') }
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }
    
   validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 5 }, presence: true
   validates :topic, presence: true
   validates :user, presence: true
   
   def up_votes
 
     votes.where(value: 1).count
   end
 
   def down_votes
 
     votes.where(value: -1).count
   end
 
   def points

     votes.sum(:value)
   end
   
   def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end

end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
    belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :sponsored_posts
    validates :name, length: { minimum: 5 }, presence: true
    validates :description, length: { minimum: 5 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    
    has_many :posts, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :favorite_posts, through: :favorites, source: :post
    
    before_save { self.email = email.downcase if email.present? }
    before_save :format_name
    before_save { self.role ||= :member }
    
    validates :name, length: { minimum: 1, maximum: 100 }, presence: true
    validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
    validates :password, length: { minimum: 6 }, allow_blank: true
    validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 254 }

    has_secure_password
    
    enum role: [:member, :admin]
    
    def format_name
        if name
            name_arr = []
            name.split.each do |i|
                name_arr << i.capitalize
            end
        self.name = name_arr.join(" ")
        end
    end 
    
    def favorite_for(post)
     favorites.where(post_id: post.id).first
    end
    
    def fav_avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(user.post.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end
    
    def avatar_url(size)
     gravatar_id = Digest::MD5::hexdigest(self.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private
 
   def update_post
     post.update_rank
   end

end

app/helpers/comments_helper.rb
module CommentsHelper
    def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.admin?)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def user_is_authorized_for_post?(post)
        current_user && (current_user == post.user || current_user.admin?)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def create_session(user)
     session[:user_id] = user.id
   end
   
   def destroy_session(user)
     session[:user_id] = nil
   end
   
   def current_user
     User.find_by(id: session[:user_id])
   end
   
end

app/helpers/topics_helper.rb
module TopicsHelper
    
    def user_is_authorized_for_topics?
        current_user && current_user.admin?
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
    def user_has_no_posts_or_comments?(post, comment)
        @user.posts.count == 0 && @user.comments.count == 0
    end
   
    
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="eg">
<head>
  <title>Rant</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span> 
           </button>
           <div class="navbar-brand rant">
             <%= link_to 'RANT', root_path %>   
           </div> 
         </div>
         <div class="collapse navbar-collapse" id="myNavbar">
           <ul class="nav navbar-nav navbar-right">
             <% if current_user %>
               <li><h4 class="rant"><%= link_to "RANTS", topics_path %></h4></li>
               <li><%= link_to ( image_tag (current_user.avatar_url(32)), class: "img-circle"), user_path(current_user) %></li>
               <li><h4 class="rant"><%= link_to "Sign Out", session_path(current_user), method: :delete %></h4></li>
             <% else %>
               <li><h4 class="rant"><%= link_to "Rants", topics_path %></h4></li>
               <li><%= link_to "", new_user_path, class: "glyphicon glyphicon-user" %></li>
               <li><%= link_to "", new_session_path, class: "glyphicon glyphicon-log-in" %></li>
             <% end %>
           </ul>
          </div>
       </div>
   </nav>  
   <% if flash[:notice] %>
     <div class="alert alert-success">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:notice] %>
     </div>
   <% elsif flash[:alert] %>
     <div class="alert alert-warning">
       <button type="button" class="close" data-dismiss="alert">&times;</button>
       <%= flash[:alert] %>
    </div>
  <% end %>
  <div class="container">
    <%= yield %> 
  </div>
  
 
</body>
</html>